# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Trash-Park
version:      0.03
version_from: lib/Trash/Park.pm
installdirs:  site
requires:
    Class::Accessor:               0
    DBD::CSV:                      0
    DBI:                           0
    File::Basename:                0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Temp:                    0
    Log::Log4perl:                 0
    Pod::Usage:                    0
    Stat::lsMode:                  0
    Sysadm::Install:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
